### ISSUE TITLE
プロフィール

### ISSUE THREAD

**Issue by ShotaroKataoka** [ShotaroKataoka/GitHubIssuesCMS_sideM#1]
```yaml
blog_title: ENTER_TITLE_of_YOUR_BLOG
author_name: ENTER_YOUR_NICK_NAME
author_description: ENTER_YOUR_SHORT_INTRODUCTION
copylight_name: ENTER_YOUR_NAME (for copyright component)
copylight_url: ENTER_YOUR_URL (for copyright component)
root_url: https://shotarokataoka.github.io/GitHubIssuesCMS_sideF/
issues_edit_page: https://github.com/ShotaroKataoka/GitHubIssuesCMS_sideM/issues
avatar_url: https://user-images.githubusercontent.com/42331656/167279203-ba5c992f-fb0c-466d-be79-ccf1b9b18407.jpg
favicon_url: https://user-images.githubusercontent.com/42331656/167279816-3bbd7fd9-3e37-4140-a2a5-1970eb4e8d48.png

# Please rewrite your SNS url
# This is an ordered SNS list
# Unnecessary items can be deleted (or commented out)
sns:
  - name: GitHub
    url: https://
  - name: Twitter
    url: https://
  - name: Facebook
    url: https://
  - name: LinkedIn
    url: https://
  - name: Instagram
    url: https://
  - name: YouTube
    url: https://
```
