### ISSUE TITLE
てすと

### ISSUE THREAD

**Issue by ShotaroKataoka** [ShotaroKataoka/GitHubIssuesCMS_sideM#2]
```yaml
# OGP. SNSなどでシェアされるときに展開される部分の設定
## OGP description. 記事の概要．
ogp_description: 記事の説明文

## OGP image. OGP画像のテーマ設定
### 'basic' | 'kill_la_kill' | Image URL
ogp_img_theme: basic
```
## title
content
